all :

c1 :
	gcc hw1.c -o a.out
	./a.out
	rm a.out
c2 :
	gcc hw2.c -o a.out
	./a.out
	rm a.out
c3 :
	gcc hw3.c -o a.out
	./a.out
	rm a.out
c4 :
	gcc hw4.c -o a.out
	./a.out
	rm a.out
c5 :
	gcc hw5.c -o a.out
	./a.out
	rm a.out

h1 :
	gcc homework01.c -o a.out
	./a.out
	rm a.out
h2 :
	gcc homework02.c -o a.out
	./a.out
	rm a.out
h3 :
	gcc homework03.c -o a.out
	./a.out
	rm a.out
h4 :
	gcc homework04.c -o a.out
	./a.out
	rm a.out
h5 :
	gcc homework05.c -o a.out
	./a.out
	rm a.out
h6 :
	gcc homework06.c -o a.out
	./a.out
	rm a.out
h7 :
	gcc homework07.c -o a.out
	./a.out
	rm a.out
h8 :
	gcc homework08.c -o a.out
	./a.out
	rm a.out
h9 :
	gcc homework09.c -o a.out
	./a.out
	rm a.out
h10 :
	gcc homework10.c -o a.out
	./a.out
	rm a.out
h11 :
	gcc homework11.c -o a.out
	./a.out
	rm a.out
h12 :
	gcc homework12.c -o a.out
	./a.out
	rm a.out
h13 :
	gcc homework13.c -o a.out
	./a.out
	rm a.out
h14 :
	gcc homework14.c -o a.out
	./a.out
	rm a.out
h15 :
	gcc homework15.c -o a.out
	./a.out
	rm a.out
h16 :
	gcc homework16.c -o a.out
	./a.out
	rm a.out
h17 :
	gcc homework17.c -o a.out
	./a.out
	rm a.out
h18 :
	gcc homework18.c -o a.out
	./a.out
	rm a.out
h19 :
	gcc homework19.c -o a.out
	./a.out
	rm a.out
h20 :
	gcc homework20.c -o a.out
	./a.out
	rm a.out
h21 :
	gcc homework21.c -o a.out
	./a.out
	rm a.out
h22 :
	gcc homework22.c -o a.out
	./a.out
	rm a.out
h23 :
	gcc homework23.c -o a.out
	./a.out
	rm a.out
h24 :
	gcc homework24.c -o a.out
	./a.out
	rm a.out
h25 :
	gcc homework25.c -o a.out
	./a.out
	rm a.out
h26 :
	gcc homework26.c -o a.out
	./a.out
	rm a.out