all :



c1 :
	gcc num1.c -o a.out
	./a.out
	rm a.out
c2 :
	gcc num3.c -o a.out
	./a.out
	rm a.out

h1 :
	gcc homework01.c -o a.out
	./a.out
	rm a.out
h2 :
	gcc homework02.c -o a.out
	./a.out
	rm a.out
h3 :
	gcc homework03.c -o a.out
	./a.out
	rm a.out
h4 :
	gcc homework04.c -o a.out
	./a.out
	rm a.out
h5 :
	gcc homework05.c -o a.out
	./a.out
	rm a.out
h6 :
	gcc homework06.c -o a.out
	./a.out
	rm a.out
h7 :
	gcc homework07.c -o a.out
	./a.out
	rm a.out
h8 :
	gcc homework08.c -o a.out
	./a.out
	rm a.out
h9 :
	gcc homework09.c -o a.out
	./a.out
	rm a.out
h10 :
	gcc homework10.c -o a.out
	./a.out
	rm a.out
h11 :
	gcc homework11.c -o a.out
	./a.out
	rm a.out